### PR TITLE
psf2bdf.pl: Support mapping multiple codepoints to a glyph

### PR DESCRIPTION
**Pull request by Vogtinator**
It collected all the supported codepoints, but didn't do anything with the
additional ones.

### CODE REVIEW

**Comment by Martchus** [comment]
Like with the previous PR I'm wondering what the impact of this is, e.g. are messages like "looks like there was a change in fonts in remote workers, I've been creating some needles for that but still on-going" from the RC channel #testing related?

**Comment by Vogtinator** [comment]
> Like with the previous PR I'm wondering what the impact of this is,

The goal of the change is that tests over ssh (which use this) use the same font as tests using direct graphics, i.e. the linux console.

> e.g. are messages like "looks like there was a change in fonts in remote workers, I've been creating some needles for that but still on-going" from the RC channel #testing related?

I'm not in that channel, but it might be. I should note that needles which show missing line drawing characters (what this PR fixes) are broken and need to be deleted.

**Review by Martchus — APPROVED** [review]
Ok, sounds good. You might want to add the explanation to the commit message. I also assume you did some kind of local testing. It would be interesting to know how you've tested it, maybe worth a remark within the README.

**Comment by Vogtinator** [comment]
> Ok, sounds good. You might want to add the explanation to the commit message.

For the font change in general? That's mostly #1, it also linkes a progress ticket.

 > I also assume you did some kind of local testing. It would be interesting to know how you've tested it, maybe worth a remark within the README.

Pretty much by following the existing instructions in the `xterm-console` script, which generates the font files. In the `xterm-console` I just ran some of the affected commands (like `dialog`).

**Review by okurz — CHANGES_REQUESTED** [review]
In the git commit message s/maping/mapping/

Can you provide more context in the git commit message like tickets or bug reports how you came to this?

**Comment by skriesch** [comment]
Yes. I close it.

**Comment by Vogtinator** [comment]
> In the git commit message s/maping/mapping/
> 
> Can you provide more context in the git commit message like tickets or bug reports how you came to this?

Done

**Review by okurz — APPROVED** [review]

**Comment by jknphy** [comment]
just wondering which frecuency os-autoinst is deployed in OSD. Because this fix would avoid to create many wrong needles in ncurses. I've just restarted one job without surrounding boxes and it is not yet applied and someone else already create wrong needle: https://openqa.suse.de/tests/6037598#step/ncurses/7 (false negative for that particular test for instance)

**Comment by Julie-CAO** [comment]
I hit the problem as well. all my test failed to install sles15sp3/15sp2/12sp5. I have created several needles but that's not enough. we need a root solution. Hope this pr can fix it, and ASAP.

**Comment by Martchus** [comment]
We wouldn't deploy today but we can if it helps you. (see https://progress.opensuse.org/projects/qa/wiki/Wiki#Common-tasks-for-team-members and https://gitlab.suse.de/openqa/osd-deployment)

EDIT: I've triggered the deployment.

**Pull request merged**
